### ISSUE TITLE
Unsatisfied link error

### ISSUE THREAD

**Issue by v01dn3ph1l1m** [iRYO400/Vlur#1]
Crash at runtime
 
 Process: app.burpy, PID: 2163
                                                                                                    java.lang.UnsatisfiedLinkError: No implementation found for long com.sadvakassov.vlur.internal.VulkanImageProcessor.initVulkanProcessor(boolean, android.content.res.AssetManager) (tried Java_com_sadvakassov_vlur_internal_VulkanImageProcessor_initVulkanProcessor and Java_com_sadvakassov_vlur_internal_VulkanImageProcessor_initVulkanProcessor__ZLandroid_content_res_AssetManager_2) - is the library loaded, e.g. System.loadLibrary?
                                                                                                    	at com.sadvakassov.vlur.internal.VulkanImageProcessor.initVulkanProcessor(Native Method)
                                                                                                    	at com.sadvakassov.vlur.internal.VulkanImageProcessor.<init>(VulkanImageProcessor.kt:11)
                                                                                                    	at com.sadvakassov.vlur.VlurState.<init>(VlurState.kt:24)
                                                                                                    	at com.sadvakassov.vlur.ComposablesKt.rememberVulkanState(Composables.kt:22)
                                                                                                    	at app.burpy.screens.searchrecipes.mood.SBMoodKt.ColorPickerScreen(SBMood.kt:65)
                                                                                                    	at app.burpy.ComposableSingletons$MainActivityKt$lambda-20$1.invoke(MainActivity.kt:350)
                                                                                                    	at app.burpy.ComposableSingletons$MainActivityKt$lambda-20$1.invoke(MainActivity.kt:350)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:139)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
                                                                                                    	at androidx.navigation.compose.NavHostKt$NavHost$14$1.invoke(NavHost.kt:308)
                                                                                                    	at androidx.navigation.compose.NavHostKt$NavHost$14$1.invoke(NavHost.kt:306)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
                                                                                                    	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)

**Comment by iRYO400** [comment]
Oh, my bad. I forgot to mention the initial step in the README. I've updated it.

To fix that, you have to call `System.loadLibrary("vlur")`:
https://github.com/iRYO400/Vlur/blob/master/sample/src/main/java/com/sadvakassov/vlur/sample/MainActivity.kt#L17

Or wait an hour, I'm uploading a wrapper I wrote in README

**Comment by v01dn3ph1l1m** [comment]
@iRYO400 thanks a bunch. looking forward to trying this out. RenderScript is deprecated and blurring HWA views is a challenge. will this work on any view?

**Comment by v01dn3ph1l1m** [comment]
@iRYO400 the blur doesnt update. i have an animation running behind the blur. that appears static. any possibility of making this realtime?

**Comment by iRYO400** [comment]
> @iRYO400 thanks a bunch. looking forward to trying this out. RenderScript is deprecated and blurring HWA views is a challenge. will this work on any view?

Yes, but further investigation is needed. For example, modifiers applied after `vlur` don't work correctly.


> @iRYO400 the blur doesnt update. i have an animation running behind the blur. that appears static. any possibility of making this realtime?

For that case, there is a library that has gone much further. Check it 
https://github.com/chrisbanes/haze
